"""initial control plane

Revision ID: b9a259ea5e19
Revises:
Create Date: 2026-09-04 21:47:53.764223
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b9a259ea5e19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers')),
    sa.UniqueConstraint('code', name=op.f('uq_ai_providers_code'))
    )
    op.create_table('cities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_v1_id', sa.BigInteger(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('names_json', sa.JSON(), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('public_id', name=op.f('uq_cities_public_id'))
    )
    op.create_index(op.f('ix_cities_legacy_v1_id'), 'cities', ['legacy_v1_id'], unique=True)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.create_table('data_import_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('imported_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('table_counts_json', sa.JSON(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_import_runs'))
    )
    op.create_index(op.f('ix_data_import_runs_source'), 'data_import_runs', ['source'], unique=False)
    op.create_index(op.f('ix_data_import_runs_status'), 'data_import_runs', ['status'], unique=False)
    op.create_table('legacy_app_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_session_id', sa.String(length=64), nullable=False),
    sa.Column('legacy_user_id', sa.BigInteger(), nullable=True),
    sa.Column('profile_context', sa.Text(), nullable=False),
    sa.Column('profile_language', sa.String(length=16), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_app_sessions'))
    )
    op.create_index(op.f('ix_legacy_app_sessions_legacy_session_id'), 'legacy_app_sessions', ['legacy_session_id'], unique=True)
    op.create_index(op.f('ix_legacy_app_sessions_legacy_user_id'), 'legacy_app_sessions', ['legacy_user_id'], unique=False)
    op.create_table('poi_types',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_v1_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poi_types')),
    sa.UniqueConstraint('name', name=op.f('uq_poi_types_name'))
    )
    op.create_index(op.f('ix_poi_types_code'), 'poi_types', ['code'], unique=True)
    op.create_index(op.f('ix_poi_types_legacy_v1_id'), 'poi_types', ['legacy_v1_id'], unique=True)
    op.create_table('prompt_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_definitions')),
    sa.UniqueConstraint('code', name=op.f('uq_prompt_definitions_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_v1_id', sa.BigInteger(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('auth_provider', sa.String(length=40), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('public_id', name=op.f('uq_users_public_id'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_legacy_v1_id'), 'users', ['legacy_v1_id'], unique=True)
    op.create_index(op.f('ix_users_provider_subject'), 'users', ['provider_subject'], unique=True)
    op.create_table('admin_audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_admin_audit_events_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_events'))
    )
    op.create_index(op.f('ix_admin_audit_events_action'), 'admin_audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_events_trace_id'), 'admin_audit_events', ['trace_id'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('service_kind', sa.String(length=20), nullable=False),
    sa.Column('adapter_code', sa.String(length=80), nullable=False),
    sa.Column('lifecycle', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('selectable', sa.Boolean(), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_ai_models_provider_id_ai_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_models')),
    sa.UniqueConstraint('provider_id', 'external_id', name=op.f('uq_ai_models_provider_id'))
    )
    op.create_table('pois',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_v1_id', sa.BigInteger(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('poi_type_id', sa.BigInteger(), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('names_json', sa.JSON(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('short_descriptions_json', sa.JSON(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=False),
    sa.Column('source_of_truth', sa.String(length=64), nullable=False),
    sa.Column('wikidata_id', sa.String(length=64), nullable=False),
    sa.Column('wikipedia_title', sa.String(length=255), nullable=False),
    sa.Column('google_place_id', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_pois_city_id_cities')),
    sa.ForeignKeyConstraint(['poi_type_id'], ['poi_types.id'], name=op.f('fk_pois_poi_type_id_poi_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pois')),
    sa.UniqueConstraint('city_id', 'slug', name=op.f('uq_pois_city_id')),
    sa.UniqueConstraint('public_id', name=op.f('uq_pois_public_id'))
    )
    op.create_index(op.f('ix_pois_city_id'), 'pois', ['city_id'], unique=False)
    op.create_index(op.f('ix_pois_google_place_id'), 'pois', ['google_place_id'], unique=False)
    op.create_index(op.f('ix_pois_legacy_v1_id'), 'pois', ['legacy_v1_id'], unique=True)
    op.create_index(op.f('ix_pois_name'), 'pois', ['name'], unique=False)
    op.create_index(op.f('ix_pois_poi_type_id'), 'pois', ['poi_type_id'], unique=False)
    op.create_index(op.f('ix_pois_slug'), 'pois', ['slug'], unique=False)
    op.create_index(op.f('ix_pois_wikidata_id'), 'pois', ['wikidata_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables_json', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_prompt_versions_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['definition_id'], ['prompt_definitions.id'], name=op.f('fk_prompt_versions_definition_id_prompt_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('definition_id', 'version', name=op.f('uq_prompt_versions_definition_id'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_roles_user_id'))
    )
    op.create_table('wallets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_v1_id', sa.BigInteger(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('public_id', name=op.f('uq_wallets_public_id'))
    )
    op.create_index(op.f('ix_wallets_legacy_v1_id'), 'wallets', ['legacy_v1_id'], unique=True)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_table('ai_routing_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('experience_code', sa.String(length=80), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('voice_mode', sa.String(length=30), nullable=False),
    sa.Column('primary_model_id', sa.Integer(), nullable=False),
    sa.Column('fallback_model_id', sa.Integer(), nullable=True),
    sa.Column('prompt_version_id', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fallback_model_id'], ['ai_models.id'], name=op.f('fk_ai_routing_profiles_fallback_model_id_ai_models')),
    sa.ForeignKeyConstraint(['primary_model_id'], ['ai_models.id'], name=op.f('fk_ai_routing_profiles_primary_model_id_ai_models')),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], name=op.f('fk_ai_routing_profiles_prompt_version_id_prompt_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_routing_profiles')),
    sa.UniqueConstraint('code', name=op.f('uq_ai_routing_profiles_code'))
    )
    op.create_index(op.f('ix_ai_routing_profiles_experience_code'), 'ai_routing_profiles', ['experience_code'], unique=False)
    op.create_table('provider_price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legacy_v1_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('pricing_json', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], name=op.f('fk_provider_price_snapshots_model_id_ai_models')),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_provider_price_snapshots_provider_id_ai_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_price_snapshots'))
    )
    op.create_index(op.f('ix_provider_price_snapshots_legacy_v1_id'), 'provider_price_snapshots', ['legacy_v1_id'], unique=True)
    op.create_table('top_ups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_v1_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('bonus_cents', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_reference', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_top_ups_user_id_users')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_top_ups_wallet_id_wallets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_top_ups'))
    )
    op.create_index(op.f('ix_top_ups_legacy_v1_id'), 'top_ups', ['legacy_v1_id'], unique=True)
    op.create_index(op.f('ix_top_ups_status'), 'top_ups', ['status'], unique=False)
    op.create_index(op.f('ix_top_ups_user_id'), 'top_ups', ['user_id'], unique=False)
    op.create_index(op.f('ix_top_ups_wallet_id'), 'top_ups', ['wallet_id'], unique=False)
    op.create_table('voice_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('routing_profile_id', sa.Integer(), nullable=False),
    sa.Column('prompt_version_id', sa.Integer(), nullable=False),
    sa.Column('primary_model_id', sa.Integer(), nullable=False),
    sa.Column('active_model_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('voice', sa.String(length=80), nullable=True),
    sa.Column('context_type', sa.String(length=40), nullable=False),
    sa.Column('context_public_id', sa.String(length=36), nullable=True),
    sa.Column('config_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_model_id'], ['ai_models.id'], name=op.f('fk_voice_sessions_active_model_id_ai_models')),
    sa.ForeignKeyConstraint(['primary_model_id'], ['ai_models.id'], name=op.f('fk_voice_sessions_primary_model_id_ai_models')),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], name=op.f('fk_voice_sessions_prompt_version_id_prompt_versions')),
    sa.ForeignKeyConstraint(['routing_profile_id'], ['ai_routing_profiles.id'], name=op.f('fk_voice_sessions_routing_profile_id_ai_routing_profiles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_voice_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_sessions'))
    )
    op.create_index(op.f('ix_voice_sessions_context_public_id'), 'voice_sessions', ['context_public_id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_public_id'), 'voice_sessions', ['public_id'], unique=True)
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_v1_id', sa.BigInteger(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('voice_session_id', sa.BigInteger(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('price_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('request_id', sa.String(length=200), nullable=True),
    sa.Column('interaction_type', sa.String(length=60), nullable=False),
    sa.Column('text_input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cached_text_input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('text_output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('audio_input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('audio_output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('audio_input_milliseconds', sa.BigInteger(), nullable=False),
    sa.Column('audio_output_milliseconds', sa.BigInteger(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('provider_cost_microusd', sa.BigInteger(), nullable=False),
    sa.Column('provider_cost_eur_cents', sa.BigInteger(), nullable=False),
    sa.Column('charged_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('gross_margin_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('margin_multiplier', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('raw_usage_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], name=op.f('fk_usage_events_model_id_ai_models')),
    sa.ForeignKeyConstraint(['price_snapshot_id'], ['provider_price_snapshots.id'], name=op.f('fk_usage_events_price_snapshot_id_provider_price_snapshots')),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_usage_events_provider_id_ai_providers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_events_user_id_users')),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_sessions.id'], name=op.f('fk_usage_events_voice_session_id_voice_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events')),
    sa.UniqueConstraint('provider_id', 'dedupe_key', name=op.f('uq_usage_events_provider_id')),
    sa.UniqueConstraint('public_id', name=op.f('uq_usage_events_public_id'))
    )
    op.create_index(op.f('ix_usage_events_legacy_v1_id'), 'usage_events', ['legacy_v1_id'], unique=True)
    op.create_index(op.f('ix_usage_events_request_id'), 'usage_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_usage_events_trace_id'), 'usage_events', ['trace_id'], unique=False)
    op.create_table('voice_turns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('voice_session_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provider_item_id', sa.String(length=200), nullable=True),
    sa.Column('tool_name', sa.String(length=120), nullable=True),
    sa.Column('tool_payload_json', sa.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_sessions.id'], name=op.f('fk_voice_turns_voice_session_id_voice_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_turns')),
    sa.UniqueConstraint('public_id', name=op.f('uq_voice_turns_public_id'))
    )
    op.create_index(op.f('ix_voice_turns_trace_id'), 'voice_turns', ['trace_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_v1_id', sa.BigInteger(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=False),
    sa.Column('usage_event_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider_cost_eur_cents', sa.BigInteger(), nullable=False),
    sa.Column('gross_margin_cents', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_cents', sa.BigInteger(), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('margin_multiplier', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=False),
    sa.Column('reference_id', sa.String(length=160), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usage_event_id'], ['usage_events.id'], name=op.f('fk_ledger_entries_usage_event_id_usage_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_entries_user_id_users')),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_ledger_entries_wallet_id_wallets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries')),
    sa.UniqueConstraint('public_id', name=op.f('uq_ledger_entries_public_id')),
    sa.UniqueConstraint('usage_event_id', 'kind', name=op.f('uq_ledger_entries_usage_event_id'))
    )
    op.create_index(op.f('ix_ledger_entries_legacy_v1_id'), 'ledger_entries', ['legacy_v1_id'], unique=True)
    op.create_index(op.f('ix_ledger_entries_trace_id'), 'ledger_entries', ['trace_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_wallet_id'), 'ledger_entries', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_wallet_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_trace_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_legacy_v1_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_voice_turns_trace_id'), table_name='voice_turns')
    op.drop_table('voice_turns')
    op.drop_index(op.f('ix_usage_events_trace_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_request_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_legacy_v1_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_voice_sessions_public_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_context_public_id'), table_name='voice_sessions')
    op.drop_table('voice_sessions')
    op.drop_index(op.f('ix_top_ups_wallet_id'), table_name='top_ups')
    op.drop_index(op.f('ix_top_ups_user_id'), table_name='top_ups')
    op.drop_index(op.f('ix_top_ups_status'), table_name='top_ups')
    op.drop_index(op.f('ix_top_ups_legacy_v1_id'), table_name='top_ups')
    op.drop_table('top_ups')
    op.drop_index(op.f('ix_provider_price_snapshots_legacy_v1_id'), table_name='provider_price_snapshots')
    op.drop_table('provider_price_snapshots')
    op.drop_index(op.f('ix_ai_routing_profiles_experience_code'), table_name='ai_routing_profiles')
    op.drop_table('ai_routing_profiles')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_legacy_v1_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_table('user_roles')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_pois_wikidata_id'), table_name='pois')
    op.drop_index(op.f('ix_pois_slug'), table_name='pois')
    op.drop_index(op.f('ix_pois_poi_type_id'), table_name='pois')
    op.drop_index(op.f('ix_pois_name'), table_name='pois')
    op.drop_index(op.f('ix_pois_legacy_v1_id'), table_name='pois')
    op.drop_index(op.f('ix_pois_google_place_id'), table_name='pois')
    op.drop_index(op.f('ix_pois_city_id'), table_name='pois')
    op.drop_table('pois')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_admin_audit_events_trace_id'), table_name='admin_audit_events')
    op.drop_index(op.f('ix_admin_audit_events_action'), table_name='admin_audit_events')
    op.drop_table('admin_audit_events')
    op.drop_index(op.f('ix_users_provider_subject'), table_name='users')
    op.drop_index(op.f('ix_users_legacy_v1_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('prompt_definitions')
    op.drop_index(op.f('ix_poi_types_legacy_v1_id'), table_name='poi_types')
    op.drop_index(op.f('ix_poi_types_code'), table_name='poi_types')
    op.drop_table('poi_types')
    op.drop_index(op.f('ix_legacy_app_sessions_legacy_user_id'), table_name='legacy_app_sessions')
    op.drop_index(op.f('ix_legacy_app_sessions_legacy_session_id'), table_name='legacy_app_sessions')
    op.drop_table('legacy_app_sessions')
    op.drop_index(op.f('ix_data_import_runs_status'), table_name='data_import_runs')
    op.drop_index(op.f('ix_data_import_runs_source'), table_name='data_import_runs')
    op.drop_table('data_import_runs')
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_legacy_v1_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
